# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -start-before=machine-scheduler -verify-misched -o - %s | FileCheck -check-prefix=GCN %s

--- |
  define amdgpu_kernel void @tinyInterleave() #0 { ret void }
  ; GCN-LABEL: tinyInterleave:
  ; GCN:       ; %bb.0:
  ; GCN-NEXT:    ; implicit-def: $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47
  ; GCN-NEXT:    ; implicit-def: $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63
  ; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
  ; GCN-NEXT:    v_mov_b32_e32 v106, v41
  ; GCN-NEXT:    v_mov_b32_e32 v102, v45
  ; GCN-NEXT:    v_max_f32_e32 v41, v45, v45
  ; GCN-NEXT:    v_max_f32_e32 v45, v61, v61
  ; GCN-NEXT:    ; implicit-def: $vgpr100
  ; GCN-NEXT:    ; implicit-def: $vgpr101
  ; GCN-NEXT:    v_max_f32_e32 v41, v100, v41
  ; GCN-NEXT:    v_max_f32_e32 v45, v101, v45
  ; GCN-NEXT:    ; implicit-def: $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79
  ; GCN-NEXT:    v_max3_f32 v45, v45, v62, v63
  ; GCN-NEXT:    v_max3_f32 v41, v41, v46, v47
  ; GCN-NEXT:    ; implicit-def: $vgpr110
  ; GCN-NEXT:    v_mov_b32_e32 v115, v67
  ; GCN-NEXT:    v_mov_b32_e32 v107, v57
  ; GCN-NEXT:    ds_bpermute_b32 v57, v110, v45
  ; GCN-NEXT:    ds_bpermute_b32 v67, v110, v41
  ; GCN-NEXT:    ; implicit-def: $vgpr112_vgpr113
  ; GCN-NEXT:    ; implicit-def: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15
  ; GCN-NEXT:    ; implicit-def: $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95
  ; GCN-NEXT:    v_mov_b32_e32 v114, v83
  ; GCN-NEXT:    ; implicit-def: $vgpr116
  ; GCN-NEXT:    v_mov_b32_e32 v104, v46
  ; GCN-NEXT:    ;;#ASMSTART
  ; GCN-NEXT:    s_waitcnt vmcnt(8)
  ; GCN-NEXT:    ;;#ASMEND
  ; GCN-NEXT:    s_waitcnt lgkmcnt(1)
  ; GCN-NEXT:    v_max3_f32 v101, v113, v45, v57
  ; GCN-NEXT:    s_waitcnt lgkmcnt(0)
  ; GCN-NEXT:    v_max3_f32 v100, v112, v41, v67
  ; GCN-NEXT:    v_pk_mul_f32 v[100:101], s[4:5], v[100:101]
  ; GCN-NEXT:    v_mov_b32_e32 v103, v61
  ; GCN-NEXT:    v_fma_f32 v41, s5, v80, -v100
  ; GCN-NEXT:    v_fma_f32 v45, s5, v81, -v100
  ; GCN-NEXT:    v_fma_f32 v46, s5, v82, -v100
  ; GCN-NEXT:    v_pk_fma_f32 v[114:115], s[4:5], v[114:115], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_mov_b32_e32 v105, v62
  ; GCN-NEXT:    v_fma_f32 v57, s5, v64, -v101
  ; GCN-NEXT:    v_fma_f32 v61, s5, v65, -v101
  ; GCN-NEXT:    v_fma_f32 v62, s5, v66, -v101
  ; GCN-NEXT:    v_pk_fma_f32 v[112:113], s[4:5], v[112:113], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    ds_read_b128 v[64:67], v116 offset:4352
  ; GCN-NEXT:    s_waitcnt lgkmcnt(0)
  ; GCN-NEXT:    buffer_inv sc0 sc1
  ; GCN-NEXT:    v_exp_f32_e32 v116, v41
  ; GCN-NEXT:    v_exp_f32_e32 v118, v45
  ; GCN-NEXT:    v_mov_b32_e32 v120, v84
  ; GCN-NEXT:    v_exp_f32_e32 v84, v46
  ; GCN-NEXT:    v_exp_f32_e32 v114, v114
  ; GCN-NEXT:    ; implicit-def: $vgpr117
  ; GCN-NEXT:    v_mov_b32_e32 v121, v68
  ; GCN-NEXT:    v_mov_b32_e32 v68, v85
  ; GCN-NEXT:    v_mov_b32_e32 v122, v86
  ; GCN-NEXT:    v_mov_b32_e32 v123, v70
  ; GCN-NEXT:    v_mov_b32_e32 v70, v87
  ; GCN-NEXT:    ds_read_b128 v[80:83], v117 offset:4352
  ; GCN-NEXT:    s_waitcnt lgkmcnt(0)
  ; GCN-NEXT:    buffer_inv sc0 sc1
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v41, v116
  ; GCN-NEXT:    v_pk_fma_f32 v[120:121], s[4:5], v[120:121], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_exp_f32_e32 v117, v57
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v45, v118
  ; GCN-NEXT:    v_pk_fma_f32 v[68:69], s[4:5], v[68:69], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_exp_f32_e32 v119, v61
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v57, v84
  ; GCN-NEXT:    v_pk_fma_f32 v[122:123], s[4:5], v[122:123], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_exp_f32_e32 v85, v62
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v61, v114
  ; GCN-NEXT:    v_pk_fma_f32 v[70:71], s[4:5], v[70:71], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_exp_f32_e32 v115, v115
  ; GCN-NEXT:    v_exp_f32_e32 v46, v112
  ; GCN-NEXT:    ; implicit-def: $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
  ; GCN-NEXT:    v_exp_f32_e32 v62, v113
  ; GCN-NEXT:    v_pack_b32_f16 v113, v57, v61
  ; GCN-NEXT:    v_pack_b32_f16 v112, v41, v45
  ; GCN-NEXT:    v_pk_mul_f32 v[16:17], v[16:17], v[46:47] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[18:19], v[18:19], v[46:47] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[20:21], v[20:21], v[46:47] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[22:23], v[22:23], v[46:47] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[24:25], v[24:25], v[46:47] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[26:27], v[26:27], v[46:47] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[28:29], v[28:29], v[46:47] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[30:31], v[30:31], v[46:47] op_sel_hi:[1,0]
  ; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1
  ; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
  ; GCN-NEXT:    v_mov_b32_e32 v86, v88
  ; GCN-NEXT:    v_mov_b32_e32 v87, v72
  ; GCN-NEXT:    v_mfma_f32_32x32x8_f16 v[16:31], v[64:65], v[112:113], v[16:31]
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v41, v117
  ; GCN-NEXT:    v_exp_f32_e32 v112, v120
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v57, v119
  ; GCN-NEXT:    v_exp_f32_e32 v68, v68
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v45, v85
  ; GCN-NEXT:    v_exp_f32_e32 v120, v122
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v46, v115
  ; GCN-NEXT:    v_exp_f32_e32 v70, v70
  ; GCN-NEXT:    v_mov_b32_e32 v72, v89
  ; GCN-NEXT:    v_mov_b32_e32 v88, v90
  ; GCN-NEXT:    v_mov_b32_e32 v89, v74
  ; GCN-NEXT:    v_pk_mul_f32 v[0:1], v[0:1], v[62:63] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[2:3], v[2:3], v[62:63] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[4:5], v[4:5], v[62:63] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[6:7], v[6:7], v[62:63] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[8:9], v[8:9], v[62:63] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[10:11], v[10:11], v[62:63] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[12:13], v[12:13], v[62:63] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pk_mul_f32 v[14:15], v[14:15], v[62:63] op_sel_hi:[1,0]
  ; GCN-NEXT:    v_pack_b32_f16 v125, v45, v46
  ; GCN-NEXT:    v_pack_b32_f16 v124, v41, v57
  ; GCN-NEXT:    v_mov_b32_e32 v74, v91
  ; GCN-NEXT:    v_mov_b32_e32 v108, v94
  ; GCN-NEXT:    v_mfma_f32_32x32x8_f16 v[0:15], v[64:65], v[124:125], v[0:15]
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v41, v112
  ; GCN-NEXT:    v_pk_fma_f32 v[64:65], s[4:5], v[86:87], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_exp_f32_e32 v113, v121
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v45, v68
  ; GCN-NEXT:    v_pk_fma_f32 v[72:73], s[4:5], v[72:73], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_exp_f32_e32 v69, v69
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v46, v120
  ; GCN-NEXT:    v_pk_fma_f32 v[86:87], s[4:5], v[88:89], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_exp_f32_e32 v121, v123
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v57, v70
  ; GCN-NEXT:    v_pack_b32_f16 v88, v41, v45
  ; GCN-NEXT:    v_pk_fma_f32 v[74:75], s[4:5], v[74:75], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_exp_f32_e32 v71, v71
  ; GCN-NEXT:    v_pack_b32_f16 v89, v46, v57
  ; GCN-NEXT:    v_mov_b32_e32 v109, v78
  ; GCN-NEXT:    v_mov_b32_e32 v78, v95
  ; GCN-NEXT:    v_mfma_f32_32x32x8_f16 v[16:31], v[66:67], v[88:89], v[16:31]
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v41, v113
  ; GCN-NEXT:    v_fma_f32 v39, s5, v39, -v100
  ; GCN-NEXT:    v_exp_f32_e32 v46, v64
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v45, v69
  ; GCN-NEXT:    v_mov_b32_e32 v88, v47
  ; GCN-NEXT:    v_mov_b32_e32 v89, v63
  ; GCN-NEXT:    v_pk_fma_f32 v[88:89], s[4:5], v[88:89], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_pack_b32_f16 v90, v41, v45
  ; GCN-NEXT:    v_fma_f32 v45, s5, v92, -v100
  ; GCN-NEXT:    v_exp_f32_e32 v62, v72
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v57, v121
  ; GCN-NEXT:    v_exp_f32_e32 v64, v86
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v61, v71
  ; GCN-NEXT:    v_exp_f32_e32 v89, v89
  ; GCN-NEXT:    v_exp_f32_e32 v88, v88
  ; GCN-NEXT:    ; implicit-def: $vgpr96_vgpr97
  ; GCN-NEXT:    ; implicit-def: $sgpr0
  ; GCN-NEXT:    ; implicit-def: $vgpr98_vgpr99
  ; GCN-NEXT:    ; implicit-def: $sgpr1
  ; GCN-NEXT:    ; implicit-def: $vgpr111
  ; GCN-NEXT:    ; implicit-def: $vgpr127
  ; GCN-NEXT:    ; implicit-def: $vgpr126
  ; GCN-NEXT:    ; implicit-def: $vgpr128
  ; GCN-NEXT:    ; iglp_opt mask(0x00000002)
  ; GCN-NEXT:    v_pack_b32_f16 v91, v57, v61
  ; GCN-NEXT:    v_fma_f32 v61, s5, v93, -v100
  ; GCN-NEXT:    v_exp_f32_e32 v72, v74
  ; GCN-NEXT:    v_mfma_f32_32x32x8_f16 v[0:15], v[66:67], v[90:91], v[0:15]
  ; GCN-NEXT:    v_pk_add_f32 v[90:91], v[116:117], v[118:119]
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v41, v46
  ; GCN-NEXT:    v_pk_fma_f32 v[66:67], s[4:5], v[108:109], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_exp_f32_e32 v47, v65
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v57, v62
  ; GCN-NEXT:    v_pk_fma_f32 v[78:79], s[4:5], v[78:79], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_exp_f32_e32 v63, v73
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v74, v64
  ; GCN-NEXT:    v_fma_f32 v92, s5, v77, -v101
  ; GCN-NEXT:    v_exp_f32_e32 v65, v87
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v86, v72
  ; GCN-NEXT:    v_pk_add_f32 v[84:85], v[84:85], v[90:91]
  ; GCN-NEXT:    v_exp_f32_e32 v73, v75
  ; GCN-NEXT:    v_pk_add_f32 v[84:85], v[114:115], v[84:85]
  ; GCN-NEXT:    v_pack_b32_f16 v75, v74, v86
  ; GCN-NEXT:    v_pk_add_f32 v[84:85], v[112:113], v[84:85]
  ; GCN-NEXT:    v_pack_b32_f16 v74, v41, v57
  ; GCN-NEXT:    v_pk_add_f32 v[68:69], v[68:69], v[84:85]
  ; GCN-NEXT:    v_exp_f32_e32 v67, v67
  ; GCN-NEXT:    v_pk_add_f32 v[68:69], v[120:121], v[68:69]
  ; GCN-NEXT:    v_mfma_f32_32x32x8_f16 v[16:31], v[80:81], v[74:75], v[16:31]
  ; GCN-NEXT:    v_exp_f32_e32 v74, v45
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v45, v47
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v75, v63
  ; GCN-NEXT:    v_pk_add_f32 v[68:69], v[70:71], v[68:69]
  ; GCN-NEXT:    v_exp_f32_e32 v79, v79
  ; GCN-NEXT:    v_pk_add_f32 v[46:47], v[46:47], v[68:69]
  ; GCN-NEXT:    v_pack_b32_f16 v86, v45, v75
  ; GCN-NEXT:    v_pk_add_f32 v[46:47], v[62:63], v[46:47]
  ; GCN-NEXT:    v_mov_b32_e32 v62, v32
  ; GCN-NEXT:    v_mov_b32_e32 v63, v48
  ; GCN-NEXT:    v_mov_b32_e32 v48, v33
  ; GCN-NEXT:    v_mov_b32_e32 v32, v34
  ; GCN-NEXT:    v_mov_b32_e32 v33, v50
  ; GCN-NEXT:    v_mov_b32_e32 v50, v35
  ; GCN-NEXT:    v_mov_b32_e32 v34, v36
  ; GCN-NEXT:    v_mov_b32_e32 v35, v52
  ; GCN-NEXT:    v_mov_b32_e32 v52, v37
  ; GCN-NEXT:    v_pk_fma_f32 v[36:37], s[4:5], v[62:63], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_fma_f32 v41, s5, v76, -v101
  ; GCN-NEXT:    v_exp_f32_e32 v75, v41
  ; GCN-NEXT:    v_fma_f32 v41, s5, v55, -v101
  ; GCN-NEXT:    v_exp_f32_e32 v77, v41
  ; GCN-NEXT:    v_fma_f32 v41, s5, v56, -v101
  ; GCN-NEXT:    v_exp_f32_e32 v76, v39
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v57, v65
  ; GCN-NEXT:    v_fma_f32 v39, s5, v40, -v100
  ; GCN-NEXT:    v_exp_f32_e32 v40, v61
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v61, v73
  ; GCN-NEXT:    v_exp_f32_e32 v66, v66
  ; GCN-NEXT:    v_exp_f32_e32 v56, v39
  ; GCN-NEXT:    v_mov_b32_e32 v39, v54
  ; GCN-NEXT:    v_pack_b32_f16 v87, v57, v61
  ; GCN-NEXT:    v_pk_add_f32 v[46:47], v[64:65], v[46:47]
  ; GCN-NEXT:    v_exp_f32_e32 v37, v37
  ; GCN-NEXT:    v_mfma_f32_32x32x8_f16 v[0:15], v[80:81], v[86:87], v[0:15]
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v93, v74
  ; GCN-NEXT:    v_exp_f32_e32 v78, v78
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v54, v40
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v55, v66
  ; GCN-NEXT:    v_exp_f32_e32 v57, v41
  ; GCN-NEXT:    v_exp_f32_e32 v41, v92
  ; GCN-NEXT:    v_pk_add_f32 v[46:47], v[72:73], v[46:47]
  ; GCN-NEXT:    v_exp_f32_e32 v36, v36
  ; GCN-NEXT:    v_pk_fma_f32 v[48:49], s[4:5], v[48:49], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_pk_add_f32 v[46:47], v[74:75], v[46:47]
  ; GCN-NEXT:    v_exp_f32_e32 v49, v49
  ; GCN-NEXT:    v_exp_f32_e32 v48, v48
  ; GCN-NEXT:    v_pk_fma_f32 v[32:33], s[4:5], v[32:33], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_pk_add_f32 v[46:47], v[40:41], v[46:47]
  ; GCN-NEXT:    v_exp_f32_e32 v33, v33
  ; GCN-NEXT:    v_exp_f32_e32 v32, v32
  ; GCN-NEXT:    v_pk_fma_f32 v[50:51], s[4:5], v[50:51], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_pk_add_f32 v[46:47], v[66:67], v[46:47]
  ; GCN-NEXT:    v_exp_f32_e32 v51, v51
  ; GCN-NEXT:    v_exp_f32_e32 v50, v50
  ; GCN-NEXT:    v_pk_fma_f32 v[34:35], s[4:5], v[34:35], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_pk_add_f32 v[46:47], v[78:79], v[46:47]
  ; GCN-NEXT:    v_exp_f32_e32 v35, v35
  ; GCN-NEXT:    v_exp_f32_e32 v34, v34
  ; GCN-NEXT:    v_pk_fma_f32 v[52:53], s[4:5], v[52:53], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_pk_add_f32 v[36:37], v[36:37], v[46:47]
  ; GCN-NEXT:    v_exp_f32_e32 v53, v53
  ; GCN-NEXT:    v_exp_f32_e32 v52, v52
  ; GCN-NEXT:    v_pk_fma_f32 v[38:39], s[4:5], v[38:39], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_pk_add_f32 v[36:37], v[48:49], v[36:37]
  ; GCN-NEXT:    v_exp_f32_e32 v39, v39
  ; GCN-NEXT:    v_exp_f32_e32 v38, v38
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[32:33], v[36:37]
  ; GCN-NEXT:    v_pk_fma_f32 v[80:81], s[4:5], v[106:107], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[50:51], v[32:33]
  ; GCN-NEXT:    v_mov_b32_e32 v86, v42
  ; GCN-NEXT:    v_mov_b32_e32 v87, v58
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[34:35], v[32:33]
  ; GCN-NEXT:    v_exp_f32_e32 v81, v81
  ; GCN-NEXT:    v_exp_f32_e32 v80, v80
  ; GCN-NEXT:    v_pk_fma_f32 v[86:87], s[4:5], v[86:87], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_mov_b32_e32 v58, v43
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[52:53], v[32:33]
  ; GCN-NEXT:    v_exp_f32_e32 v87, v87
  ; GCN-NEXT:    v_exp_f32_e32 v86, v86
  ; GCN-NEXT:    v_pk_fma_f32 v[42:43], s[4:5], v[58:59], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_mov_b32_e32 v45, v60
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[38:39], v[32:33]
  ; GCN-NEXT:    v_exp_f32_e32 v43, v43
  ; GCN-NEXT:    v_exp_f32_e32 v42, v42
  ; GCN-NEXT:    v_pk_fma_f32 v[44:45], s[4:5], v[44:45], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v64, v78
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[76:77], v[32:33]
  ; GCN-NEXT:    v_exp_f32_e32 v45, v45
  ; GCN-NEXT:    v_exp_f32_e32 v44, v44
  ; GCN-NEXT:    v_pk_fma_f32 v[58:59], s[4:5], v[102:103], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[56:57], v[32:33]
  ; GCN-NEXT:    v_exp_f32_e32 v59, v59
  ; GCN-NEXT:    v_exp_f32_e32 v58, v58
  ; GCN-NEXT:    v_pk_fma_f32 v[60:61], s[4:5], v[104:105], v[100:101] neg_lo:[0,0,1] neg_hi:[0,0,1]
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[80:81], v[32:33]
  ; GCN-NEXT:    v_exp_f32_e32 v61, v61
  ; GCN-NEXT:    v_exp_f32_e32 v60, v60
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[86:87], v[32:33]
  ; GCN-NEXT:    v_pack_b32_f16 v35, v55, v64
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[42:43], v[32:33]
  ; GCN-NEXT:    v_pack_b32_f16 v34, v93, v54
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[44:45], v[32:33]
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v36, v75
  ; GCN-NEXT:    v_mfma_f32_32x32x8_f16 v[16:31], v[82:83], v[34:35], v[16:31]
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[58:59], v[32:33]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[60:61], v[32:33]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_pk_add_f32 v[32:33], v[88:89], v[32:33]
  ; GCN-NEXT:    s_nop 5
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v67
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v79
  ; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v41
  ; GCN-NEXT:    ds_bpermute_b32 v16, v110, v32
  ; GCN-NEXT:    ds_bpermute_b32 v17, v110, v33
  ; GCN-NEXT:    s_waitcnt lgkmcnt(0)
  ; GCN-NEXT:    v_pack_b32_f16 v17, v18, v19
  ; GCN-NEXT:    v_pack_b32_f16 v16, v36, v20
  ; GCN-NEXT:    s_nop 1
  ; GCN-NEXT:    v_mfma_f32_32x32x8_f16 v[0:15], v[82:83], v[16:17], v[0:15]
  ; GCN-NEXT:    s_nop 7
  ; GCN-NEXT:    s_nop 2
  ; GCN-NEXT:    v_perm_b32 v0, v98, v96, s0
  ; GCN-NEXT:    v_perm_b32 v1, v98, v96, s1
  ; GCN-NEXT:    v_perm_b32 v2, v99, v97, s0
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    ds_write_b32 v111, v0
  ; GCN-NEXT:    v_lshl_add_u32 v0, v127, 1, v111
  ; GCN-NEXT:    v_perm_b32 v3, v99, v97, s1
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt lgkmcnt(0)
  ; GCN-NEXT:    ds_write_b32 v126, v1
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt lgkmcnt(0)
  ; GCN-NEXT:    ds_write_b32 v0, v2
  ; GCN-NEXT:    v_lshl_add_u32 v0, v128, 1, v111
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt lgkmcnt(0)
  ; GCN-NEXT:    ds_write_b32 v0, v3
  ; GCN-NEXT:    s_endpgm
  attributes #0 = {"amdgpu-flat-work-group-size"="256,256"}

  !0 = !{i64 2862105}

...


---
name:            tinyInterleave
tracksRegLiveness: true
machineFunctionInfo:
  stackPtrOffsetReg: '$sgpr32'
  occupancy:       3
body:             |
  bb.0:
   liveins: $vgpr0, $sgpr0_sgpr1, $sgpr2, $sgpr3, $sgpr4
    %712:vgpr_32 = IMPLICIT_DEF
    %728:vgpr_32 = IMPLICIT_DEF
    %35:vgpr_32 = IMPLICIT_DEF
    %1979:vreg_64_align2 = IMPLICIT_DEF
    %1:sgpr_512 = IMPLICIT_DEF
    %608:vreg_512_align2 = IMPLICIT_DEF
    %621:vreg_512_align2 = IMPLICIT_DEF
    %639:vreg_512_align2 = IMPLICIT_DEF
    %654:vreg_512_align2 = IMPLICIT_DEF
    %38:vgpr_32 = IMPLICIT_DEF
    %39:vgpr_32 = IMPLICIT_DEF
    %753:vreg_64_align2 = IMPLICIT_DEF
    %751:vreg_64_align2 = IMPLICIT_DEF
    %731:sreg_32 = IMPLICIT_DEF
    %733:sreg_32 = IMPLICIT_DEF
    %753:vreg_64_align2 = IMPLICIT_DEF
    %746:vgpr_32 = IMPLICIT_DEF
    %747:vgpr_32 = IMPLICIT_DEF
    %41:vgpr_32 = IMPLICIT_DEF
    %42:vgpr_32 = IMPLICIT_DEF
    %1864:vreg_512_align2 = IMPLICIT_DEF
    %1861:vreg_512_align2 = IMPLICIT_DEF
    IGLP_OPT 2
    undef %1942.sub0:vreg_64_align2 = COPY %608.sub3:vreg_512_align2
    %1942.sub1:vreg_64_align2 = COPY %621.sub3:vreg_512_align2
    undef %1923.sub0:vreg_64_align2 = COPY %608.sub14:vreg_512_align2
    %1923.sub1:vreg_64_align2 = COPY %621.sub14:vreg_512_align2
    undef %1904.sub0:vreg_64_align2 = COPY %639.sub9:vreg_512_align2
    %1904.sub1:vreg_64_align2 = COPY %654.sub9:vreg_512_align2
    undef %1885.sub0:vreg_64_align2 = COPY %639.sub13:vreg_512_align2
    %1885.sub1:vreg_64_align2 = COPY %654.sub13:vreg_512_align2
    %758:vgpr_32 = contract nofpexcept V_MAX_F32_e32 %639.sub13:vreg_512_align2, %639.sub13:vreg_512_align2, implicit $mode, implicit $exec
    %759:vgpr_32 = contract nofpexcept V_MAX_F32_e32 %712:vgpr_32, %758:vgpr_32, implicit $mode, implicit $exec
    %760:vgpr_32 = contract nofpexcept V_MAX_F32_e32 %654.sub13:vreg_512_align2, %654.sub13:vreg_512_align2, implicit $mode, implicit $exec
    %761:vgpr_32 = contract nofpexcept V_MAX_F32_e32 %728:vgpr_32, %760:vgpr_32, implicit $mode, implicit $exec
    undef %1856.sub0:vreg_64_align2 = COPY %639.sub14:vreg_512_align2
    %1856.sub1:vreg_64_align2 = COPY %654.sub14:vreg_512_align2
    undef %1977.sub0:vreg_64_align2 = COPY %639.sub15:vreg_512_align2
    %1977.sub1:vreg_64_align2 = COPY %654.sub15:vreg_512_align2
    %764:vgpr_32 = V_MAX3_F32_e64 0, %761:vgpr_32, 0, %654.sub14:vreg_512_align2, 0, %654.sub15:vreg_512_align2, 0, 0, implicit $mode, implicit $exec
    %765:vgpr_32 = V_MAX3_F32_e64 0, %759:vgpr_32, 0, %639.sub14:vreg_512_align2, 0, %639.sub15:vreg_512_align2, 0, 0, implicit $mode, implicit $exec
    %766:vgpr_32 = DS_BPERMUTE_B32 %35:vgpr_32, %765:vgpr_32, 0, implicit $exec
    %767:vgpr_32 = DS_BPERMUTE_B32 %35:vgpr_32, %764:vgpr_32, 0, implicit $exec
    undef %1959.sub1:vreg_64_align2 = V_MAX3_F32_e64 0, %1979.sub1:vreg_64_align2, 0, %764:vgpr_32, 0, %767:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %1959.sub0:vreg_64_align2 = V_MAX3_F32_e64 0, %1979.sub0:vreg_64_align2, 0, %765:vgpr_32, 0, %766:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %771:vreg_64_align2 = contract nofpexcept V_PK_MUL_F32 8, %1.sub4_sub5:sgpr_512, 8, %1959:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %774:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %608.sub0:vreg_512_align2, 1, %771.sub0:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    undef %1918.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %774:vgpr_32, implicit $mode, implicit $exec
    %776:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %608.sub1:vreg_512_align2, 1, %771.sub0:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    undef %1899.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %776:vgpr_32, implicit $mode, implicit $exec
    %778:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %608.sub2:vreg_512_align2, 1, %771.sub0:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    %779:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %608.sub12:vreg_512_align2, 1, %771.sub0:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    undef %1930.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %779:vgpr_32, implicit $mode, implicit $exec
    %781:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %608.sub13:vreg_512_align2, 1, %771.sub0:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    %782:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %639.sub7:vreg_512_align2, 1, %771.sub0:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    undef %1912.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %782:vgpr_32, implicit $mode, implicit $exec
    %783:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %639.sub8:vreg_512_align2, 1, %771.sub0:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    %785:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %621.sub0:vreg_512_align2, 1, %771.sub1:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    %1918.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %785:vgpr_32, implicit $mode, implicit $exec
    %787:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %621.sub1:vreg_512_align2, 1, %771.sub1:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    %1899.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %787:vgpr_32, implicit $mode, implicit $exec
    %789:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %621.sub2:vreg_512_align2, 1, %771.sub1:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    %790:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %621.sub12:vreg_512_align2, 1, %771.sub1:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    %1930.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %790:vgpr_32, implicit $mode, implicit $exec
    %792:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %621.sub13:vreg_512_align2, 1, %771.sub1:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    %793:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %654.sub7:vreg_512_align2, 1, %771.sub1:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    %1912.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %793:vgpr_32, implicit $mode, implicit $exec
    %794:vgpr_32 = contract nofpexcept V_FMA_F32_e64 0, %1.sub5:sgpr_512, 0, %654.sub8:vreg_512_align2, 1, %771.sub1:vreg_64_align2, 0, 0, implicit $mode, implicit $exec
    undef %1941.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %794:vgpr_32, implicit $mode, implicit $exec
    %1941.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %783:vgpr_32, implicit $mode, implicit $exec
    %798:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1904:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1922.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %798.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1922.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %798.sub0:vreg_64_align2, implicit $mode, implicit $exec
    undef %1903.sub0:vreg_64_align2 = COPY %639.sub10:vreg_512_align2
    %1903.sub1:vreg_64_align2 = COPY %654.sub10:vreg_512_align2
    %806:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1903:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1884.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %806.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1884.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %806.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %654.sub10:vreg_512_align2 = COPY %639.sub11:vreg_512_align2
    %814:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %654.sub10_sub11:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1976.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %814.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1976.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %814.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %639.sub13:vreg_512_align2 = COPY %654.sub12:vreg_512_align2
    %822:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %639.sub12_sub13:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1940.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %822.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1940.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %822.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %829:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1885:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1921.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %829.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1921.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %829.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %836:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1856:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1902.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %836.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1902.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %836.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %843:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1977:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1883.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %843.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1883.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %843.sub0:vreg_64_align2, implicit $mode, implicit $exec
    undef %1870.sub0:vreg_64_align2 = COPY %608.sub4:vreg_512_align2
    %1870.sub1:vreg_64_align2 = COPY %621.sub4:vreg_512_align2
    %621.sub4:vreg_512_align2 = COPY %608.sub5:vreg_512_align2
    undef %1957.sub0:vreg_64_align2 = COPY %608.sub6:vreg_512_align2
    %1957.sub1:vreg_64_align2 = COPY %621.sub6:vreg_512_align2
    %621.sub6:vreg_512_align2 = COPY %608.sub7:vreg_512_align2
    undef %1920.sub0:vreg_64_align2 = COPY %608.sub8:vreg_512_align2
    %1920.sub1:vreg_64_align2 = COPY %621.sub8:vreg_512_align2
    %621.sub8:vreg_512_align2 = COPY %608.sub9:vreg_512_align2
    undef %1882.sub0:vreg_64_align2 = COPY %608.sub10:vreg_512_align2
    %1882.sub1:vreg_64_align2 = COPY %621.sub10:vreg_512_align2
    %621.sub10:vreg_512_align2 = COPY %608.sub11:vreg_512_align2
    undef %1974.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %789:vgpr_32, implicit $mode, implicit $exec
    %1974.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %778:vgpr_32, implicit $mode, implicit $exec
    %861:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1942:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1956.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %861.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1956.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %861.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %868:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1870:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1938.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %868.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1938.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %868.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %875:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %621.sub4_sub5:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1919.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %875.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1919.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %875.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %882:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1957:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1900.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %882.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1900.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %882.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %889:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %621.sub6_sub7:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1881.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %889.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1881.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %889.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %896:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1920:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1863.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %896.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1863.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %896.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %903:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %621.sub8_sub9:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1973.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %903.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1973.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %903.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %910:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1882:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1955.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %910.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1955.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %910.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %917:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %621.sub10_sub11:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1937.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %917.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1937.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %917.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %926:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1918:vreg_64_align2, 8, %1899:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %928:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1974:vreg_64_align2, 8, %926:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %929:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1956:vreg_64_align2, 8, %928:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %930:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1938:vreg_64_align2, 8, %929:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %931:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1919:vreg_64_align2, 8, %930:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %932:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1900:vreg_64_align2, 8, %931:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %933:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1881:vreg_64_align2, 8, %932:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %934:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1863:vreg_64_align2, 8, %933:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %935:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1973:vreg_64_align2, 8, %934:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %936:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1955:vreg_64_align2, 8, %935:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %937:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1937:vreg_64_align2, 8, %936:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %621.sub14:vreg_512_align2 = COPY %608.sub15:vreg_512_align2
    undef %1860.sub0:vreg_64_align2 = COPY %639.sub0:vreg_512_align2
    %1860.sub1:vreg_64_align2 = COPY %654.sub0:vreg_512_align2
    %654.sub0:vreg_512_align2 = COPY %639.sub1:vreg_512_align2
    undef %1954.sub0:vreg_64_align2 = COPY %639.sub2:vreg_512_align2
    %1954.sub1:vreg_64_align2 = COPY %654.sub2:vreg_512_align2
    %654.sub2:vreg_512_align2 = COPY %639.sub3:vreg_512_align2
    undef %1917.sub0:vreg_64_align2 = COPY %639.sub4:vreg_512_align2
    %1917.sub1:vreg_64_align2 = COPY %654.sub4:vreg_512_align2
    %654.sub4:vreg_512_align2 = COPY %639.sub5:vreg_512_align2
    %639.sub7:vreg_512_align2 = COPY %654.sub6:vreg_512_align2
    undef %1857.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %792:vgpr_32, implicit $mode, implicit $exec
    %1857.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %781:vgpr_32, implicit $mode, implicit $exec
    %949:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1923:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1970.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %949.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1970.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %949.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %956:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %621.sub14_sub15:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1952.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %956.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1952.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %956.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %963:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1860:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1934.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %963.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1934.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %963.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %970:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %654.sub0_sub1:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1915.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %970.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1915.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %970.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %977:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1954:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1896.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %977.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1896.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %977.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %984:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %654.sub2_sub3:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1875.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %984.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1875.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %984.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %991:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1917:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1986.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %991.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1986.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %991.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %998:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %654.sub4_sub5:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1968.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %998.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1968.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %998.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1005:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %639.sub6_sub7:vreg_512_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1950.sub1:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %1005.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1950.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %1005.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1013:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1930:vreg_64_align2, 8, %937:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1014:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1857:vreg_64_align2, 8, %1013:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1015:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1970:vreg_64_align2, 8, %1014:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1016:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1952:vreg_64_align2, 8, %1015:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1017:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1934:vreg_64_align2, 8, %1016:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1018:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1915:vreg_64_align2, 8, %1017:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1019:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1896:vreg_64_align2, 8, %1018:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1020:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1875:vreg_64_align2, 8, %1019:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1021:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1986:vreg_64_align2, 8, %1020:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1022:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1968:vreg_64_align2, 8, %1021:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1023:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1950:vreg_64_align2, 8, %1022:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1025:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1912:vreg_64_align2, 8, %1023:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1026:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1941:vreg_64_align2, 8, %1025:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1027:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1922:vreg_64_align2, 8, %1026:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1028:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1884:vreg_64_align2, 8, %1027:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1029:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1976:vreg_64_align2, 8, %1028:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1030:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1940:vreg_64_align2, 8, %1029:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1031:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1921:vreg_64_align2, 8, %1030:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1032:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1902:vreg_64_align2, 8, %1031:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %114:vreg_64_align2 = contract nofpexcept V_PK_ADD_F32 8, %1883:vreg_64_align2, 8, %1032:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1971.sub0:vreg_64_align2 = DS_BPERMUTE_B32 %35:vgpr_32, %114.sub0:vreg_64_align2, 0, implicit $exec
    %1971.sub1:vreg_64_align2 = DS_BPERMUTE_B32 %35:vgpr_32, %114.sub1:vreg_64_align2, 0, implicit $exec
    %1035:vreg_64_align2 = contract nofpexcept V_PK_FMA_F32 8, %1.sub4_sub5:sgpr_512, 8, %1979:vreg_64_align2, 11, %771:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    undef %1069.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %1035.sub1:vreg_64_align2, implicit $mode, implicit $exec
    undef %1893.sub0:vreg_64_align2 = nofpexcept V_EXP_F32_e32 %1035.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1864.sub0_sub1:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1864.sub0_sub1:vreg_512_align2, 0, %1893:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1864.sub2_sub3:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1864.sub2_sub3:vreg_512_align2, 0, %1893:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1864.sub4_sub5:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1864.sub4_sub5:vreg_512_align2, 0, %1893:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1864.sub6_sub7:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1864.sub6_sub7:vreg_512_align2, 0, %1893:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1864.sub8_sub9:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1864.sub8_sub9:vreg_512_align2, 0, %1893:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1864.sub10_sub11:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1864.sub10_sub11:vreg_512_align2, 0, %1893:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1864.sub12_sub13:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1864.sub12_sub13:vreg_512_align2, 0, %1893:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1864.sub14_sub15:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1864.sub14_sub15:vreg_512_align2, 0, %1893:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1861.sub0_sub1:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1861.sub0_sub1:vreg_512_align2, 0, %1069:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1861.sub2_sub3:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1861.sub2_sub3:vreg_512_align2, 0, %1069:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1861.sub4_sub5:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1861.sub4_sub5:vreg_512_align2, 0, %1069:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1861.sub6_sub7:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1861.sub6_sub7:vreg_512_align2, 0, %1069:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1861.sub8_sub9:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1861.sub8_sub9:vreg_512_align2, 0, %1069:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1861.sub10_sub11:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1861.sub10_sub11:vreg_512_align2, 0, %1069:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1861.sub12_sub13:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1861.sub12_sub13:vreg_512_align2, 0, %1069:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1861.sub14_sub15:vreg_512_align2 = contract nofpexcept V_PK_MUL_F32 8, %1861.sub14_sub15:vreg_512_align2, 0, %1069:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %1096:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1918.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1097:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1899.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1098:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1974.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1099:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1956.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1100:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1938.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1101:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1919.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1102:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1900.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1103:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1881.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1104:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1863.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1105:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1973.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1106:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1955.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1107:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1937.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1108:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1930.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1109:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1857.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1110:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1970.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1111:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1952.sub0:vreg_64_align2, implicit $mode, implicit $exec
    %1112:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1918.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1113:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1899.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1114:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1974.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1115:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1956.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1116:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1938.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1117:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1919.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1118:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1900.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1119:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1881.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1120:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1863.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1121:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1973.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1122:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1955.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1123:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1937.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1124:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1930.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1125:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1857.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1126:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1970.sub1:vreg_64_align2, implicit $mode, implicit $exec
    %1127:vgpr_32 = nofpexcept V_CVT_F16_F32_e32 %1952.sub1:vreg_64_align2, implicit $mode, implicit $exec
    INLINEASM &"s_waitcnt vmcnt($0)", 57 /* sideeffect mayload maystore isconvergent attdialect */, 13 /* imm */, 8, !0
    undef %1871.sub1:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1098:vgpr_32, 0, %1099:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %1871.sub0:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1096:vgpr_32, 0, %1097:vgpr_32, 0, 0, implicit $mode, implicit $exec
    undef %1983.sub1:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1102:vgpr_32, 0, %1103:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %1983.sub0:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1100:vgpr_32, 0, %1101:vgpr_32, 0, 0, implicit $mode, implicit $exec
    undef %1965.sub1:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1106:vgpr_32, 0, %1107:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %1965.sub0:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1104:vgpr_32, 0, %1105:vgpr_32, 0, 0, implicit $mode, implicit $exec
    undef %1947.sub1:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1110:vgpr_32, 0, %1111:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %1947.sub0:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1108:vgpr_32, 0, %1109:vgpr_32, 0, 0, implicit $mode, implicit $exec
    undef %1927.sub1:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1114:vgpr_32, 0, %1115:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %1927.sub0:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1112:vgpr_32, 0, %1113:vgpr_32, 0, 0, implicit $mode, implicit $exec
    undef %1909.sub1:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1118:vgpr_32, 0, %1119:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %1909.sub0:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1116:vgpr_32, 0, %1117:vgpr_32, 0, 0, implicit $mode, implicit $exec
    undef %1890.sub1:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1122:vgpr_32, 0, %1123:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %1890.sub0:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1120:vgpr_32, 0, %1121:vgpr_32, 0, 0, implicit $mode, implicit $exec
    undef %1867.sub1:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1126:vgpr_32, 0, %1127:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %1867.sub0:vreg_64_align2 = nofpexcept V_PACK_B32_F16_e64 0, %1124:vgpr_32, 0, %1125:vgpr_32, 0, 0, implicit $mode, implicit $exec
    %1152:vreg_128_align2 = DS_READ_B128_gfx9 %38:vgpr_32, 4352, 0, implicit $exec
    %1864:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_mac_vgprcd_e64 %1152.sub0_sub1:vreg_128_align2, %1871:vreg_64_align2, %1864:vreg_512_align2, 0, 0, 0, implicit $mode, implicit $exec
    %1864:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_mac_vgprcd_e64 %1152.sub2_sub3:vreg_128_align2, %1983:vreg_64_align2, %1864:vreg_512_align2, 0, 0, 0, implicit $mode, implicit $exec
    %1861:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_mac_vgprcd_e64 %1152.sub0_sub1:vreg_128_align2, %1927:vreg_64_align2, %1861:vreg_512_align2, 0, 0, 0, implicit $mode, implicit $exec
    %1861:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_mac_vgprcd_e64 %1152.sub2_sub3:vreg_128_align2, %1909:vreg_64_align2, %1861:vreg_512_align2, 0, 0, 0, implicit $mode, implicit $exec
    %1175:vreg_128_align2 = DS_READ_B128_gfx9 %39:vgpr_32, 4352, 0, implicit $exec
    %1864:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_mac_vgprcd_e64 %1175.sub0_sub1:vreg_128_align2, %1965:vreg_64_align2, %1864:vreg_512_align2, 0, 0, 0, implicit $mode, implicit $exec
    %1864:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_mac_vgprcd_e64 %1175.sub2_sub3:vreg_128_align2, %1947:vreg_64_align2, %1864:vreg_512_align2, 0, 0, 0, implicit $mode, implicit $exec
    %1861:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_mac_vgprcd_e64 %1175.sub0_sub1:vreg_128_align2, %1890:vreg_64_align2, %1861:vreg_512_align2, 0, 0, 0, implicit $mode, implicit $exec
    %1861:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_mac_vgprcd_e64 %1175.sub2_sub3:vreg_128_align2, %1867:vreg_64_align2, %1861:vreg_512_align2, 0, 0, 0, implicit $mode, implicit $exec
    %1194:vgpr_32 = V_PERM_B32_e64 %753.sub0:vreg_64_align2, %751.sub0:vreg_64_align2, %731:sreg_32, implicit $exec
    %1195:vgpr_32 = V_PERM_B32_e64 %753.sub0:vreg_64_align2, %751.sub0:vreg_64_align2, %733:sreg_32, implicit $exec
    %1198:vgpr_32 = V_PERM_B32_e64 %753.sub1:vreg_64_align2, %751.sub1:vreg_64_align2, %731:sreg_32, implicit $exec
    %1199:vgpr_32 = V_PERM_B32_e64 %753.sub1:vreg_64_align2, %751.sub1:vreg_64_align2, %733:sreg_32, implicit $exec
    DS_WRITE_B32_gfx9 %746:vgpr_32, %1194:vgpr_32, 0, 0, implicit $exec
    DS_WRITE_B32_gfx9 %747:vgpr_32, %1195:vgpr_32, 0, 0, implicit $exec
    %1200:vgpr_32 = V_LSHL_ADD_U32_e64 %41:vgpr_32, 1, %746:vgpr_32, implicit $exec
    DS_WRITE_B32_gfx9 %1200:vgpr_32, %1198:vgpr_32, 0, 0, implicit $exec
    %1201:vgpr_32 = V_LSHL_ADD_U32_e64 %42:vgpr_32, 1, %746:vgpr_32, implicit $exec
    DS_WRITE_B32_gfx9 %1201:vgpr_32, %1199:vgpr_32, 0, 0, implicit $exec
    S_ENDPGM 0
...
