; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple sparc | FileCheck %s -check-prefixes=NAKED-32
; RUN: llc < %s -mtriple sparc64 | FileCheck %s -check-prefixes=NAKED-64

declare dso_local void @main()

define dso_local void @naked() naked "frame-pointer"="all" {
; NAKED-32-LABEL: naked:
; NAKED-32:         .cfi_startproc
; NAKED-32-NEXT:  ! %bb.0:
; NAKED-32-NEXT:    call main
; NAKED-32-NEXT:    nop
;
; NAKED-64-LABEL: naked:
; NAKED-64:         .cfi_startproc
; NAKED-64-NEXT:  ! %bb.0:
; NAKED-64-NEXT:    call main
; NAKED-64-NEXT:    nop
  call void @main()
  unreachable
}

define dso_local void @normal() "frame-pointer"="all" {
; NAKED-32-LABEL: normal:
; NAKED-32:         .cfi_startproc
; NAKED-32-NEXT:  ! %bb.0:
; NAKED-32-NEXT:    save %sp, -96, %sp
; NAKED-32-NEXT:    .cfi_def_cfa_register %fp
; NAKED-32-NEXT:    .cfi_window_save
; NAKED-32-NEXT:    .cfi_register %o7, %i7
; NAKED-32-NEXT:    call main
; NAKED-32-NEXT:    nop
;
; NAKED-64-LABEL: normal:
; NAKED-64:         .cfi_startproc
; NAKED-64-NEXT:  ! %bb.0:
; NAKED-64-NEXT:    save %sp, -176, %sp
; NAKED-64-NEXT:    .cfi_def_cfa_register %fp
; NAKED-64-NEXT:    .cfi_window_save
; NAKED-64-NEXT:    .cfi_register %o7, %i7
; NAKED-64-NEXT:    call main
; NAKED-64-NEXT:    nop
  call void @main()
  unreachable
}
