; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt --bpf-check-and-opt-ir -S -mtriple=bpf-pc-linux < %s | FileCheck %s

; Generated from the following C code:

; #define __uptr __attribute__((address_space(272)))
;
; void simple_store(void __uptr *foo) {
;   *((volatile int __uptr *)(foo + 16)) = 0xdead;
;   *((volatile int __uptr *)(foo + 12)) = 0xbeef;
; }
;
; void separate_addr_store(void __uptr *foo, void __uptr *bar) {
;   *((volatile int __uptr *)(foo + 16)) = 0xdead;
;   *((volatile int __uptr *)(bar + 12)) = 0xbeef;
; }
;
; int simple_load(int __uptr *foo) {
;   return *foo;
; }
;
; Using the following command:
;
;   clang --target=bpf -O2 -S -emit-llvm -o t.ll t.c

define void @simple_store(ptr addrspace(272) %foo) {
; CHECK-LABEL: define void @simple_store(
; CHECK-SAME: ptr addrspace(272) [[FOO:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[FOO1:%.*]] = addrspacecast ptr addrspace(272) [[FOO]] to ptr
; CHECK-NEXT:    [[ADD_PTR2:%.*]] = getelementptr inbounds i8, ptr [[FOO1]], i64 16
; CHECK-NEXT:    store volatile i32 57005, ptr [[ADD_PTR2]], align 4
; CHECK-NEXT:    [[ADD_PTR13:%.*]] = getelementptr inbounds i8, ptr [[FOO1]], i64 12
; CHECK-NEXT:    store volatile i32 48879, ptr [[ADD_PTR13]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(272) %foo, i64 16
  store volatile i32 57005, ptr addrspace(272) %add.ptr, align 4
  %add.ptr1 = getelementptr inbounds i8, ptr addrspace(272) %foo, i64 12
  store volatile i32 48879, ptr addrspace(272) %add.ptr1, align 4
  ret void
}

define void @separate_addr_store(ptr addrspace(272) %foo, ptr addrspace(272) %bar) {
; CHECK-LABEL: define void @separate_addr_store(
; CHECK-SAME: ptr addrspace(272) [[FOO:%.*]], ptr addrspace(272) [[BAR:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[BAR3:%.*]] = addrspacecast ptr addrspace(272) [[BAR]] to ptr
; CHECK-NEXT:    [[FOO1:%.*]] = addrspacecast ptr addrspace(272) [[FOO]] to ptr
; CHECK-NEXT:    [[ADD_PTR2:%.*]] = getelementptr inbounds i8, ptr [[FOO1]], i64 16
; CHECK-NEXT:    store volatile i32 57005, ptr [[ADD_PTR2]], align 4
; CHECK-NEXT:    [[ADD_PTR14:%.*]] = getelementptr inbounds i8, ptr [[BAR3]], i64 12
; CHECK-NEXT:    store volatile i32 48879, ptr [[ADD_PTR14]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(272) %foo, i64 16
  store volatile i32 57005, ptr addrspace(272) %add.ptr, align 4
  %add.ptr1 = getelementptr inbounds i8, ptr addrspace(272) %bar, i64 12
  store volatile i32 48879, ptr addrspace(272) %add.ptr1, align 4
  ret void
}

define i32 @simple_load(ptr addrspace(272) %foo) {
; CHECK-LABEL: define i32 @simple_load(
; CHECK-SAME: ptr addrspace(272) [[FOO:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[FOO1:%.*]] = addrspacecast ptr addrspace(272) [[FOO]] to ptr
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[FOO1]], align 4
; CHECK-NEXT:    ret i32 [[TMP0]]
;
entry:
  %0 = load i32, ptr addrspace(272) %foo, align 4
  ret i32 %0
}
