# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64-- -run-pass=legalizer %s -o - | FileCheck %s

---
name: fpowi_s64_zero
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_s64_zero
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $d0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+00
    ; CHECK-NEXT: $d0 = COPY [[C]](s64)
      %0:_(s64) = COPY $d0
      %1:_(s32) = COPY $w0
      %2:_(s32) = G_CONSTANT i32 0
      %3:_(s64) = G_FPOWI %0, %2(s32)
      $d0 = COPY %3(s64)
...

---
name: fpowi_s32_zero
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_s32_zero
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $s0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 1.000000e+00
    ; CHECK-NEXT: $s0 = COPY [[C]](s32)
      %0:_(s32) = COPY $s0
      %1:_(s32) = COPY $w0
      %2:_(s32) = G_CONSTANT i32 0
      %3:_(s32) = G_FPOWI %0, %2(s32)
      $s0 = COPY %3(s32)
...

---
name: fpowi_positive
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_positive
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $d0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(s64) = G_FMUL [[COPY2]], [[COPY]]
    ; CHECK-NEXT: [[FMUL1:%[0-9]+]]:_(s64) = G_FMUL [[FMUL]], [[COPY]]
    ; CHECK-NEXT: [[FMUL2:%[0-9]+]]:_(s64) = G_FMUL [[FMUL1]], [[COPY]]
    ; CHECK-NEXT: [[FMUL3:%[0-9]+]]:_(s64) = G_FMUL [[FMUL2]], [[COPY]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(s64) = COPY [[FMUL3]](s64)
    ; CHECK-NEXT: $d0 = COPY [[COPY3]](s64)
      %0:_(s64) = COPY $d0
      %1:_(s32) = COPY $w0
      %2:_(s32) = G_CONSTANT i32 5
      %3:_(s64) = G_FPOWI %0, %2(s32)
      $d0 = COPY %3(s64)
...

---
name: fpowi_s64_negative
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_s64_negative
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $d0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(s64) = G_FMUL [[COPY2]], [[COPY]]
    ; CHECK-NEXT: [[FMUL1:%[0-9]+]]:_(s64) = G_FMUL [[FMUL]], [[COPY]]
    ; CHECK-NEXT: [[FMUL2:%[0-9]+]]:_(s64) = G_FMUL [[FMUL1]], [[COPY]]
    ; CHECK-NEXT: [[FMUL3:%[0-9]+]]:_(s64) = G_FMUL [[FMUL2]], [[COPY]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+00
    ; CHECK-NEXT: [[FDIV:%[0-9]+]]:_(s64) = G_FDIV [[C]], [[FMUL3]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(s64) = COPY [[FDIV]](s64)
    ; CHECK-NEXT: $d0 = COPY [[COPY3]](s64)
      %0:_(s64) = COPY $d0
      %1:_(s32) = COPY $w0
      %2:_(s32) = G_CONSTANT i32 -5
      %3:_(s64) = G_FPOWI %0, %2(s32)
      $d0 = COPY %3(s64)
...

---
name: fpowi_s32_negative
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_s32_negative
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $s0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(s32) = G_FMUL [[COPY2]], [[COPY]]
    ; CHECK-NEXT: [[FMUL1:%[0-9]+]]:_(s32) = G_FMUL [[FMUL]], [[COPY]]
    ; CHECK-NEXT: [[FMUL2:%[0-9]+]]:_(s32) = G_FMUL [[FMUL1]], [[COPY]]
    ; CHECK-NEXT: [[FMUL3:%[0-9]+]]:_(s32) = G_FMUL [[FMUL2]], [[COPY]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 1.000000e+00
    ; CHECK-NEXT: [[FDIV:%[0-9]+]]:_(s32) = G_FDIV [[C]], [[FMUL3]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY [[FDIV]](s32)
    ; CHECK-NEXT: $s0 = COPY [[COPY3]](s32)
      %0:_(s32) = COPY $s0
      %1:_(s32) = COPY $w0
      %2:_(s32) = G_CONSTANT i32 -5
      %3:_(s32) = G_FPOWI %0, %2(s32)
      $s0 = COPY %3(s32)
...

---
name: fpowi_libcall
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_libcall
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $d0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $d0 = COPY [[COPY]](s64)
    ; CHECK-NEXT: $w0 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: BL &__powidf2, csr_aarch64_aapcs, implicit-def $lr, implicit $sp, implicit $d0, implicit $w0, implicit-def $d0
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s64) = COPY $d0
    ; CHECK-NEXT: $d0 = COPY [[COPY2]](s64)
      %0:_(s64) = COPY $d0
      %1:_(s32) = COPY $w0
      %2:_(s64) = G_FPOWI %0, %1(s32)
      $d0 = COPY %2(s64)
...
