; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=asan -S | FileCheck %s
; RUN: opt < %s -passes=tsan -S | FileCheck %s
; RUN: opt < %s -passes=hwasan -S | FileCheck %s --check-prefixes=CHECK-HWASAN
; RUN: opt < %s -passes=dfsan -dfsan-track-origins=1  -S | FileCheck %s
; RUN: opt < %s -passes='module(sancov-module)' -sanitizer-coverage-level=3 -sanitizer-coverage-control-flow -S | FileCheck %s
; RUN: opt < %s -passes='module(sanmd-module)' -sanitizer-metadata-atomics -S | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @naked_function() naked {
; CHECK-LABEL: define void @naked_function(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    call void asm sideeffect "nop", ""()
; CHECK-NEXT:    unreachable
;
  call void asm sideeffect "nop", ""()
  unreachable
}

define void @naked_function_with_asan() sanitize_address naked {
; CHECK-LABEL: define void @naked_function_with_asan(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    call void asm sideeffect "nop", ""()
; CHECK-NEXT:    unreachable
;
  call void asm sideeffect "nop", ""()
  unreachable
}

define void @naked_function_with_tsan() sanitize_thread naked {
; CHECK-LABEL: define void @naked_function_with_tsan(
; CHECK-SAME: ) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    call void asm sideeffect "nop", ""()
; CHECK-NEXT:    unreachable
;
  call void asm sideeffect "nop", ""()
  unreachable
}

define void @naked_function_with_msan() sanitize_memory naked {
; CHECK-LABEL: define void @naked_function_with_msan(
; CHECK-SAME: ) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:    call void asm sideeffect "nop", ""()
; CHECK-NEXT:    unreachable
;
  call void asm sideeffect "nop", ""()
  unreachable
}

define void @naked_function_with_hwasan() sanitize_hwaddress naked {
; CHECK-HWASAN-LABEL: define void @naked_function_with_hwasan(
; CHECK-HWASAN-SAME: ) #[[ATTR4:[0-9]+]] personality ptr @__hwasan_personality_thunk {
; CHECK-HWASAN-NEXT:    call void asm sideeffect "nop", ""()
; CHECK-HWASAN-NEXT:    unreachable
;
  call void asm sideeffect "nop", ""()
  unreachable
}
