; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple arm | FileCheck %s -check-prefixes=NAKED-ALE
; RUN: llc < %s -mtriple armeb | FileCheck %s -check-prefixes=NAKED-ABE
; RUN: llc < %s -mtriple thumb | FileCheck %s -check-prefixes=NAKED-TLE
; RUN: llc < %s -mtriple thumbeb | FileCheck %s -check-prefixes=NAKED-TBE

declare dso_local void @main()

define dso_local void @naked() naked "frame-pointer"="all" {
; NAKED-ALE-LABEL: naked:
; NAKED-ALE:       @ %bb.0:
; NAKED-ALE-NEXT:    bl main
;
; NAKED-ABE-LABEL: naked:
; NAKED-ABE:       @ %bb.0:
; NAKED-ABE-NEXT:    bl main
;
; NAKED-TLE-LABEL: naked:
; NAKED-TLE:       @ %bb.0:
; NAKED-TLE-NEXT:    bl main
;
; NAKED-TBE-LABEL: naked:
; NAKED-TBE:       @ %bb.0:
; NAKED-TBE-NEXT:    bl main
  call void @main()
  unreachable
}

define dso_local void @normal() "frame-pointer"="all" {
; NAKED-ALE-LABEL: normal:
; NAKED-ALE:       @ %bb.0:
; NAKED-ALE-NEXT:    push {r11, lr}
; NAKED-ALE-NEXT:    mov r11, sp
; NAKED-ALE-NEXT:    bl main
;
; NAKED-ABE-LABEL: normal:
; NAKED-ABE:       @ %bb.0:
; NAKED-ABE-NEXT:    push {r11, lr}
; NAKED-ABE-NEXT:    mov r11, sp
; NAKED-ABE-NEXT:    bl main
;
; NAKED-TLE-LABEL: normal:
; NAKED-TLE:       @ %bb.0:
; NAKED-TLE-NEXT:    push {r7, lr}
; NAKED-TLE-NEXT:    add r7, sp, #0
; NAKED-TLE-NEXT:    bl main
;
; NAKED-TBE-LABEL: normal:
; NAKED-TBE:       @ %bb.0:
; NAKED-TBE-NEXT:    push {r7, lr}
; NAKED-TBE-NEXT:    add r7, sp, #0
; NAKED-TBE-NEXT:    bl main
  call void @main()
  unreachable
}
