; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=mips --fp-contract off < %s | FileCheck %s -check-prefix=SOFT-FLOAT-32-FPC-OFF
; RUN: llc -mtriple=mips --fp-contract on < %s | FileCheck %s -check-prefix=SOFT-FLOAT-32-FPC-ON
; RUN: llc -mtriple=mips --fp-contract fast < %s | FileCheck %s -check-prefix=SOFT-FLOAT-32-FPC-FAST
; RUN: llc -mtriple=mips -mcpu mips32r2 --fp-contract off < %s | FileCheck %s -check-prefix=SOFT-FLOAT-32R2-FPC-OFF
; RUN: llc -mtriple=mips -mcpu mips32r2 --fp-contract on < %s | FileCheck %s -check-prefix=SOFT-FLOAT-32R2-FPC-ON
; RUN: llc -mtriple=mips -mcpu mips32r2 --fp-contract fast < %s | FileCheck %s -check-prefix=SOFT-FLOAT-32R2-FPC-FAST
; RUN: llc -mtriple=mips64 --fp-contract off < %s | FileCheck %s -check-prefix=SOFT-FLOAT-64-FPC-OFF
; RUN: llc -mtriple=mips64 --fp-contract on < %s | FileCheck %s -check-prefix=SOFT-FLOAT-64-FPC-ON
; RUN: llc -mtriple=mips64 --fp-contract fast < %s | FileCheck %s -check-prefix=SOFT-FLOAT-64-FPC-FAST
; RUN: llc -mtriple=mips64 -mcpu mips64r2 --fp-contract off < %s | FileCheck %s -check-prefix=SOFT-FLOAT-64R2-FPC-OFF
; RUN: llc -mtriple=mips64 -mcpu mips64r2 --fp-contract on < %s | FileCheck %s -check-prefix=SOFT-FLOAT-64R2-FPC-ON
; RUN: llc -mtriple=mips64 -mcpu mips64r2 --fp-contract fast < %s | FileCheck %s -check-prefix=SOFT-FLOAT-64R2-FPC-FAST

define float @fmuladd_intrinsic_f32(float %a, float %b, float %c) #0 {
; SOFT-FLOAT-32-FPC-OFF-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-32-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-32-FPC-OFF-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-OFF-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-OFF-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-OFF-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-OFF-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-OFF-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jal __mulsf3
; SOFT-FLOAT-32-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-32-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jal __addsf3
; SOFT-FLOAT-32-FPC-OFF-NEXT:    move $5, $16
; SOFT-FLOAT-32-FPC-OFF-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-OFF-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-OFF-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32-FPC-ON-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-32-FPC-ON:       # %bb.0:
; SOFT-FLOAT-32-FPC-ON-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-ON-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-ON-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-ON-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-ON-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-ON-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32-FPC-ON-NEXT:    jal __mulsf3
; SOFT-FLOAT-32-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-32-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-ON-NEXT:    jal __addsf3
; SOFT-FLOAT-32-FPC-ON-NEXT:    move $5, $16
; SOFT-FLOAT-32-FPC-ON-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-ON-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-ON-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32-FPC-FAST-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-32-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-32-FPC-FAST-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-FAST-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-FAST-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-FAST-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-FAST-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-FAST-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jal __mulsf3
; SOFT-FLOAT-32-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-32-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jal __addsf3
; SOFT-FLOAT-32-FPC-FAST-NEXT:    move $5, $16
; SOFT-FLOAT-32-FPC-FAST-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-FAST-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-FAST-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-OFF-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-32R2-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jal __mulsf3
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jal __addsf3
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    move $5, $16
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-ON-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-32R2-FPC-ON:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jal __mulsf3
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jal __addsf3
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    move $5, $16
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-FAST-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-32R2-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jal __mulsf3
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jal __addsf3
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    move $5, $16
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-64-FPC-OFF-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-64-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-64-FPC-OFF-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jal __mulsf3
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jal __addsf3
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64-FPC-OFF-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-OFF-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-OFF-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64-FPC-ON-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-64-FPC-ON:       # %bb.0:
; SOFT-FLOAT-64-FPC-ON-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-ON-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-ON-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-ON-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64-FPC-ON-NEXT:    jal __mulsf3
; SOFT-FLOAT-64-FPC-ON-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64-FPC-ON-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64-FPC-ON-NEXT:    jal __addsf3
; SOFT-FLOAT-64-FPC-ON-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64-FPC-ON-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-ON-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-ON-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64-FPC-FAST-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-64-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-64-FPC-FAST-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jal __mulsf3
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jal __addsf3
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64-FPC-FAST-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-FAST-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-FAST-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-OFF-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-64R2-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jal __mulsf3
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jal __addsf3
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-ON-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-64R2-FPC-ON:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jal __mulsf3
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jal __addsf3
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-FAST-LABEL: fmuladd_intrinsic_f32:
; SOFT-FLOAT-64R2-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jal __mulsf3
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jal __addsf3
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    daddiu $sp, $sp, 16
    %result = call float @llvm.fmuladd.f32(float %a, float %b, float %c)
    ret float %result
}

define double @fmuladd_intrinsic_f64(double %a, double %b, double %c) #0 {
; SOFT-FLOAT-32-FPC-OFF-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-32-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-32-FPC-OFF-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-OFF-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-OFF-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-OFF-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jal __muldf3
; SOFT-FLOAT-32-FPC-OFF-NEXT:    nop
; SOFT-FLOAT-32-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-OFF-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32-FPC-OFF-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jal __adddf3
; SOFT-FLOAT-32-FPC-OFF-NEXT:    move $5, $3
; SOFT-FLOAT-32-FPC-OFF-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-OFF-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32-FPC-ON-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-32-FPC-ON:       # %bb.0:
; SOFT-FLOAT-32-FPC-ON-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-ON-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-ON-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-ON-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-ON-NEXT:    jal __muldf3
; SOFT-FLOAT-32-FPC-ON-NEXT:    nop
; SOFT-FLOAT-32-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-ON-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32-FPC-ON-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32-FPC-ON-NEXT:    jal __adddf3
; SOFT-FLOAT-32-FPC-ON-NEXT:    move $5, $3
; SOFT-FLOAT-32-FPC-ON-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-ON-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32-FPC-FAST-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-32-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-32-FPC-FAST-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-FAST-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-FAST-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-FAST-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jal __muldf3
; SOFT-FLOAT-32-FPC-FAST-NEXT:    nop
; SOFT-FLOAT-32-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-FAST-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32-FPC-FAST-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jal __adddf3
; SOFT-FLOAT-32-FPC-FAST-NEXT:    move $5, $3
; SOFT-FLOAT-32-FPC-FAST-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-FAST-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-OFF-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-32R2-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jal __muldf3
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    nop
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jal __adddf3
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    move $5, $3
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-ON-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-32R2-FPC-ON:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jal __muldf3
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    nop
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jal __adddf3
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    move $5, $3
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-FAST-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-32R2-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jal __muldf3
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    nop
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jal __adddf3
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    move $5, $3
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-64-FPC-OFF-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-64-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-64-FPC-OFF-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jal __muldf3
; SOFT-FLOAT-64-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jal __adddf3
; SOFT-FLOAT-64-FPC-OFF-NEXT:    move $5, $16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-OFF-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-OFF-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64-FPC-ON-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-64-FPC-ON:       # %bb.0:
; SOFT-FLOAT-64-FPC-ON-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-ON-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-ON-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-ON-NEXT:    jal __muldf3
; SOFT-FLOAT-64-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-64-FPC-ON-NEXT:    jal __adddf3
; SOFT-FLOAT-64-FPC-ON-NEXT:    move $5, $16
; SOFT-FLOAT-64-FPC-ON-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-ON-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-ON-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64-FPC-FAST-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-64-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-64-FPC-FAST-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jal __muldf3
; SOFT-FLOAT-64-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jal __adddf3
; SOFT-FLOAT-64-FPC-FAST-NEXT:    move $5, $16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-FAST-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-FAST-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-OFF-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-64R2-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jal __muldf3
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jal __adddf3
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    move $5, $16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-ON-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-64R2-FPC-ON:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jal __muldf3
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jal __adddf3
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    move $5, $16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-FAST-LABEL: fmuladd_intrinsic_f64:
; SOFT-FLOAT-64R2-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jal __muldf3
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jal __adddf3
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    move $5, $16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    daddiu $sp, $sp, 16
    %result = call double @llvm.fmuladd.f64(double %a, double %b, double %c)
    ret double %result
}

define float @fmuladd_contract_f32(float %a, float %b, float %c) #0 {
; SOFT-FLOAT-32-FPC-OFF-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-32-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-32-FPC-OFF-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-OFF-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-OFF-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-OFF-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-OFF-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-OFF-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jal __mulsf3
; SOFT-FLOAT-32-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-32-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jal __addsf3
; SOFT-FLOAT-32-FPC-OFF-NEXT:    move $5, $16
; SOFT-FLOAT-32-FPC-OFF-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-OFF-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-OFF-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32-FPC-ON-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-32-FPC-ON:       # %bb.0:
; SOFT-FLOAT-32-FPC-ON-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-ON-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-ON-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-ON-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-ON-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-ON-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32-FPC-ON-NEXT:    jal __mulsf3
; SOFT-FLOAT-32-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-32-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-ON-NEXT:    jal __addsf3
; SOFT-FLOAT-32-FPC-ON-NEXT:    move $5, $16
; SOFT-FLOAT-32-FPC-ON-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-ON-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-ON-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32-FPC-FAST-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-32-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-32-FPC-FAST-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-FAST-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-FAST-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-FAST-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-FAST-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-FAST-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jal __mulsf3
; SOFT-FLOAT-32-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-32-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jal __addsf3
; SOFT-FLOAT-32-FPC-FAST-NEXT:    move $5, $16
; SOFT-FLOAT-32-FPC-FAST-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-FAST-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-FAST-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-OFF-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-32R2-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jal __mulsf3
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jal __addsf3
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    move $5, $16
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-ON-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-32R2-FPC-ON:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jal __mulsf3
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jal __addsf3
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    move $5, $16
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-FAST-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-32R2-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    .cfi_offset 16, -8
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jal __mulsf3
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jal __addsf3
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    move $5, $16
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-64-FPC-OFF-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-64-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-64-FPC-OFF-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jal __mulsf3
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jal __addsf3
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64-FPC-OFF-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-OFF-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-OFF-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64-FPC-ON-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-64-FPC-ON:       # %bb.0:
; SOFT-FLOAT-64-FPC-ON-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-ON-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-ON-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-ON-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64-FPC-ON-NEXT:    jal __mulsf3
; SOFT-FLOAT-64-FPC-ON-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64-FPC-ON-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64-FPC-ON-NEXT:    jal __addsf3
; SOFT-FLOAT-64-FPC-ON-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64-FPC-ON-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-ON-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-ON-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64-FPC-FAST-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-64-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-64-FPC-FAST-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jal __mulsf3
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jal __addsf3
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64-FPC-FAST-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-FAST-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-FAST-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-OFF-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-64R2-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jal __mulsf3
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jal __addsf3
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-ON-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-64R2-FPC-ON:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jal __mulsf3
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jal __addsf3
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-FAST-LABEL: fmuladd_contract_f32:
; SOFT-FLOAT-64R2-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sll $4, $4, 0
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jal __mulsf3
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sll $5, $5, 0
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sll $4, $2, 0
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jal __addsf3
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sll $5, $16, 0
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    daddiu $sp, $sp, 16
    %product = fmul float %a, %b
    %result = fadd float %product, %c
    ret float %result
}

define double @fmuladd_contract_f64(double %a, double %b, double %c) #0 {
; SOFT-FLOAT-32-FPC-OFF-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-32-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-32-FPC-OFF-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-OFF-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-OFF-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-OFF-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jal __muldf3
; SOFT-FLOAT-32-FPC-OFF-NEXT:    nop
; SOFT-FLOAT-32-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-OFF-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32-FPC-OFF-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jal __adddf3
; SOFT-FLOAT-32-FPC-OFF-NEXT:    move $5, $3
; SOFT-FLOAT-32-FPC-OFF-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-OFF-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32-FPC-ON-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-32-FPC-ON:       # %bb.0:
; SOFT-FLOAT-32-FPC-ON-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-ON-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-ON-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-ON-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-ON-NEXT:    jal __muldf3
; SOFT-FLOAT-32-FPC-ON-NEXT:    nop
; SOFT-FLOAT-32-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-ON-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32-FPC-ON-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32-FPC-ON-NEXT:    jal __adddf3
; SOFT-FLOAT-32-FPC-ON-NEXT:    move $5, $3
; SOFT-FLOAT-32-FPC-ON-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-ON-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32-FPC-FAST-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-32-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-32-FPC-FAST-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32-FPC-FAST-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32-FPC-FAST-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32-FPC-FAST-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jal __muldf3
; SOFT-FLOAT-32-FPC-FAST-NEXT:    nop
; SOFT-FLOAT-32-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-32-FPC-FAST-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32-FPC-FAST-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jal __adddf3
; SOFT-FLOAT-32-FPC-FAST-NEXT:    move $5, $3
; SOFT-FLOAT-32-FPC-FAST-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-32-FPC-FAST-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-OFF-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-32R2-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jal __muldf3
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    nop
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jal __adddf3
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    move $5, $3
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-OFF-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-ON-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-32R2-FPC-ON:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jal __muldf3
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    nop
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jal __adddf3
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    move $5, $3
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-ON-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-32R2-FPC-FAST-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-32R2-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    addiu $sp, $sp, -24
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    .cfi_def_cfa_offset 24
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    .cfi_offset 31, -4
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jal __muldf3
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    nop
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    lw $6, 40($sp)
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    lw $7, 44($sp)
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jal __adddf3
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    move $5, $3
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-32R2-FPC-FAST-NEXT:    addiu $sp, $sp, 24
;
; SOFT-FLOAT-64-FPC-OFF-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-64-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-64-FPC-OFF-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-OFF-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-OFF-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jal __muldf3
; SOFT-FLOAT-64-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jal __adddf3
; SOFT-FLOAT-64-FPC-OFF-NEXT:    move $5, $16
; SOFT-FLOAT-64-FPC-OFF-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-OFF-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-OFF-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64-FPC-ON-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-64-FPC-ON:       # %bb.0:
; SOFT-FLOAT-64-FPC-ON-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-ON-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-ON-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-ON-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-ON-NEXT:    jal __muldf3
; SOFT-FLOAT-64-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-64-FPC-ON-NEXT:    jal __adddf3
; SOFT-FLOAT-64-FPC-ON-NEXT:    move $5, $16
; SOFT-FLOAT-64-FPC-ON-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-ON-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-ON-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64-FPC-FAST-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-64-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-64-FPC-FAST-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-FAST-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64-FPC-FAST-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jal __muldf3
; SOFT-FLOAT-64-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-64-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jal __adddf3
; SOFT-FLOAT-64-FPC-FAST-NEXT:    move $5, $16
; SOFT-FLOAT-64-FPC-FAST-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-FAST-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-64-FPC-FAST-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-OFF-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-64R2-FPC-OFF:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jal __muldf3
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    move $4, $2
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jal __adddf3
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    move $5, $16
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-OFF-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-ON-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-64R2-FPC-ON:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jal __muldf3
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    move $4, $2
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jal __adddf3
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    move $5, $16
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-ON-NEXT:    daddiu $sp, $sp, 16
;
; SOFT-FLOAT-64R2-FPC-FAST-LABEL: fmuladd_contract_f64:
; SOFT-FLOAT-64R2-FPC-FAST:       # %bb.0:
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    daddiu $sp, $sp, -16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_def_cfa_offset 16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    sd $16, 0($sp) # 8-byte Folded Spill
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_offset 31, -8
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    .cfi_offset 16, -16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jal __muldf3
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    move $16, $6
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    move $4, $2
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jal __adddf3
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    move $5, $16
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    ld $16, 0($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    jr $ra
; SOFT-FLOAT-64R2-FPC-FAST-NEXT:    daddiu $sp, $sp, 16
    %product = fmul double %a, %b
    %result = fadd double %product, %c
    ret double %result
}

attributes #0 = { "use-soft-float"="true" }

declare float @llvm.fmuladd.f32(float %a, float %b, float %c)
declare double @llvm.fmuladd.f64(double %a, double %b, double %c)
