; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple riscv32 | FileCheck %s -check-prefixes=NAKED-32
; RUN: llc < %s -mtriple riscv64 | FileCheck %s -check-prefixes=NAKED-64

declare dso_local void @main()

define dso_local void @naked() naked "frame-pointer"="all" {
; NAKED-32-LABEL: naked:
; NAKED-32:       # %bb.0:
; NAKED-32-NEXT:    call main
;
; NAKED-64-LABEL: naked:
; NAKED-64:       # %bb.0:
; NAKED-64-NEXT:    call main
  call void @main()
  unreachable
}

define dso_local void @normal() "frame-pointer"="all" {
; NAKED-32-LABEL: normal:
; NAKED-32:       # %bb.0:
; NAKED-32-NEXT:    addi sp, sp, -16
; NAKED-32-NEXT:    .cfi_def_cfa_offset 16
; NAKED-32-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; NAKED-32-NEXT:    sw s0, 8(sp) # 4-byte Folded Spill
; NAKED-32-NEXT:    .cfi_offset ra, -4
; NAKED-32-NEXT:    .cfi_offset s0, -8
; NAKED-32-NEXT:    addi s0, sp, 16
; NAKED-32-NEXT:    .cfi_def_cfa s0, 0
; NAKED-32-NEXT:    call main
;
; NAKED-64-LABEL: normal:
; NAKED-64:       # %bb.0:
; NAKED-64-NEXT:    addi sp, sp, -16
; NAKED-64-NEXT:    .cfi_def_cfa_offset 16
; NAKED-64-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NAKED-64-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; NAKED-64-NEXT:    .cfi_offset ra, -8
; NAKED-64-NEXT:    .cfi_offset s0, -16
; NAKED-64-NEXT:    addi s0, sp, 16
; NAKED-64-NEXT:    .cfi_def_cfa s0, 0
; NAKED-64-NEXT:    call main
  call void @main()
  unreachable
}
