// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
 // REQUIRES: amdgpu-registered-target
 // RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu verde -emit-llvm -o - %s | FileCheck %s --check-prefixes=VERDE
 // RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu tonga -emit-llvm -o - %s | FileCheck %s --check-prefixes=GFX8
 // RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1100 -emit-llvm -o - %s | FileCheck %s --check-prefixes=GFX11

void foo(__buffer_rsrc_t);

// VERDE-LABEL: @bar(
// VERDE-NEXT:  entry:
// VERDE-NEXT:    tail call void @foo(ptr addrspace(8) [[RSRC:%.*]]) #[[ATTR2:[0-9]+]]
// VERDE-NEXT:    ret void
//
// GFX8-LABEL: @bar(
// GFX8-NEXT:  entry:
// GFX8-NEXT:    tail call void @foo(ptr addrspace(8) [[RSRC:%.*]]) #[[ATTR2:[0-9]+]]
// GFX8-NEXT:    ret void
//
// GFX11-LABEL: @bar(
// GFX11-NEXT:  entry:
// GFX11-NEXT:    tail call void @foo(ptr addrspace(8) [[RSRC:%.*]]) #[[ATTR2:[0-9]+]]
// GFX11-NEXT:    ret void
//
void bar(__buffer_rsrc_t rsrc) {
  foo(rsrc);
}
