// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu verde -emit-llvm -o - %s | FileCheck %s

#pragma OPENCL EXTENSION cl_khr_fp16 : enable

typedef short v2i16 __attribute__((ext_vector_type(2)));
typedef int v2i32 __attribute__((ext_vector_type(2)));
typedef half v2f16 __attribute__((ext_vector_type(2)));
typedef float v2f32 __attribute__((ext_vector_type(2)));
typedef short v4i16 __attribute__((ext_vector_type(4)));
typedef int v4i32 __attribute__((ext_vector_type(4)));
typedef half v4f16 __attribute__((ext_vector_type(4)));
typedef float v4f32 __attribute__((ext_vector_type(4)));

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.i8(i8 [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_i8(char vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_i8(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.i16(i16 [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_i16(short vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_i16(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.i32(i32 [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_i32(int vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_i32(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.f16(half [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_f16(half vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_f16(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.f32(float [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_f32(float vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_f32(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v2i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v2i16(<2 x i16> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v2i16(v2i16 vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v2i16(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v2i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v2i32(<2 x i32> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v2i32(v2i32 vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v2i32(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v2f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v2f16(<2 x half> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v2f16(v2f16 vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v2f16(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v2f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v2f32(<2 x float> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v2f32(v2f32 vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v2f32(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v4i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v4i16(<4 x i16> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v4i16(v4i16 vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v4i16(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v4i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v4i32(<4 x i32> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v4i32(v4i32 vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v4i32(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v4f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v4f16(<4 x half> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v4f16(v4f16 vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v4f16(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v4f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v4f32(<4 x float> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v4f32(v4f32 vdata, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v4f32(vdata, rsrc, /*offset=*/0, /*soffset=*/0, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_i8_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.i8(i8 [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_i8_non_const_args(char vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_i8(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_i16_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.i16(i16 [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_i16_non_const_args(short vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_i16(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_i32_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.i32(i32 [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_i32_non_const_args(int vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_i32(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_f16_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.f16(half [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_f16_non_const_args(half vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_f16(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_f32_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.f32(float [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_f32_non_const_args(float vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_f32(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v2i16_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v2i16(<2 x i16> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v2i16_non_const_args(v2i16 vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v2i16(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v2i32_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v2i32(<2 x i32> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v2i32_non_const_args(v2i32 vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v2i32(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v2f16_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v2f16(<2 x half> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v2f16_non_const_args(v2f16 vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v2f16(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v2f32_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v2f32(<2 x float> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v2f32_non_const_args(v2f32 vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v2f32(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v4i16_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v4i16(<4 x i16> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v4i16_non_const_args(v4i16 vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v4i16(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v4i32_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v4i32(<4 x i32> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v4i32_non_const_args(v4i32 vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v4i32(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v4f16_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v4f16(<4 x half> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v4f16_non_const_args(v4f16 vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v4f16(vdata, rsrc, offset, soffset, /*aux=*/0);
}

// CHECK-LABEL: @test_amdgcn_raw_ptr_buffer_store_v4f32_non_const_args(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.raw.ptr.buffer.store.v4f32(<4 x float> [[VDATA:%.*]], ptr addrspace(8) [[RSRC:%.*]], i32 [[OFFSET:%.*]], i32 [[SOFFSET:%.*]], i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_raw_ptr_buffer_store_v4f32_non_const_args(v4f32 vdata, int offset, int soffset, __amdgpu_buffer_rsrc_t rsrc) {
  __builtin_amdgcn_raw_ptr_buffer_store_v4f32(vdata, rsrc, offset, soffset, /*aux=*/0);
}
