; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -o - %s -mtriple=aarch64-linux-gnu | FileCheck %s --check-prefixes=CHECK

define i64 @square(i64 %a, ptr %p) local_unnamed_addr #0 {
; CHECK-LABEL: square:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmov d0, x0
; CHECK-NEXT:    mov x0, xzr
; CHECK-NEXT:    cnt v0.8b, v0.8b
; CHECK-NEXT:    addv b0, v0.8b
; CHECK-NEXT:    str d0, [x1]
; CHECK-NEXT:    ret
  %2 = call i64 @llvm.ctpop(i64 %a)
  store i64 %2, ptr %p
  ret i64 0
}

declare i64 @llvm.ctpop.i64(i64) #1

