; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=aarch64 | FileCheck %s

define i32 @f(ptr %0, i41 %1, ptr %2) {
; CHECK-LABEL: f:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and w9, w1, #0x1
; CHECK-NEXT:    mov w10, #1 // =0x1
; CHECK-NEXT:    mov x8, x0
; CHECK-NEXT:    cmp w9, #1
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    adc x9, xzr, x10
; CHECK-NEXT:    str x9, [x2]
; CHECK-NEXT:    str xzr, [x8]
; CHECK-NEXT:    ret
  %new0 = and i41 %1, 1
  %last = trunc i41 %new0 to i1
  %4 = add i64 0, 1
  %5 = zext i1 %last to i64
  %6 = add i64 %4, %5
  %7 = icmp ult i64 %4, 0
  %8 = icmp ult i64 %6, %4
  %9 = and i1 %7, %8
  %10 = zext i1 %9 to i64
  store i64 %6, ptr %2, align 8
  store i64 %10, ptr %0, align 8
  ret i32 0
}
