; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define float @tanAtanInverse(float %x) {
; CHECK-LABEL: define float @tanAtanInverse(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[CALL:%.*]] = call float @atanf(float [[X]])
; CHECK-NEXT:    [[CALL1:%.*]] = call float @tanf(float [[CALL]])
; CHECK-NEXT:    ret float [[CALL1]]
;
  %call = call float @atanf(float %x)
  %call1 = call float @tanf(float %call)
  ret float %call1
}

define float @atanhTanhInverse(float %x) {
; CHECK-LABEL: define float @atanhTanhInverse(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[CALL:%.*]] = call float @tanhf(float [[X]])
; CHECK-NEXT:    [[CALL1:%.*]] = call float @atanhf(float [[CALL]])
; CHECK-NEXT:    ret float [[CALL1]]
;
  %call = call float @tanhf(float %x)
  %call1 = call float @atanhf(float %call)
  ret float %call1
}

define float @sinhAsinhInverse(float %x) {
; CHECK-LABEL: define float @sinhAsinhInverse(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[CALL:%.*]] = call float @asinhf(float [[X]])
; CHECK-NEXT:    [[CALL1:%.*]] = call float @sinhf(float [[CALL]])
; CHECK-NEXT:    ret float [[CALL1]]
;
  %call = call float @asinhf(float %x)
  %call1 = call float @sinhf(float %call)
  ret float %call1
}

define float @coshAcoshInverse(float %x)  {
; CHECK-LABEL: define float @coshAcoshInverse(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[CALL:%.*]] = call float @acoshf(float [[X]])
; CHECK-NEXT:    [[CALL1:%.*]] = call float @coshf(float [[CALL]])
; CHECK-NEXT:    ret float [[CALL1]]
;
  %call = call float @acoshf(float %x)
  %call1 = call float @coshf(float %call)
  ret float %call1
}

declare float @asinhf(float)
declare float @sinhf(float)
declare float @acoshf(float)
declare float @coshf(float)
declare float @tanhf(float)
declare float @atanhf(float)
declare float @tanf(float)
declare float @atanf(float)
