name: LLVM Premerge Checks

permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/premerge.yaml
  push:
    branches:
      - 'main'

jobs:
  premerge-checks-windows:
    if: github.repository_owner == 'llvm'
    runs-on: llvm-premerge-windows-runners
    concurrency:
      group: ${{ github.workflow }}-windows-${{ github.event.pull_request.number || github.sha }}
      cancel-in-progress: true
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.14
      - name: Build and Test
        continue-on-error: true
        run: |
          echo test

